package it.polimi.ingsw.Server.ServerToClient;

public enum Change {MERGE,CONQUER,MOTHERNATURE,MOVESTUDENT,CLOUD,TAKECLOUD,PLAYCLOWN,PLAYHERBALIST,PLAYINNKEEPER,PLAYPRINCESS,PLAYSTORYTELLER,PLAYTHIEF,PLAYMERCHANT,DEFAULT
}
